import { applyShelfRules } from "./shelf";
import type { Skill } from "./types";

/**
 * Curated demo inventory for the improved LVL LTD marketplace.
 * Includes deep/standard/outline mix so shelf rules are visible.
 * agent-memory is the live per-call runtime skill.
 */
const RAW: Skill[] = [
  {
    id: "agent-memory",
    name: "Agent Memory",
    summary:
      "Persistent wallet-scoped key-value memory. remember / recall / list / forget metered per call in USDC on Base via x402. Best-effort durability.",
    category: "Memory",
    tier: "starter",
    price_usd: 0.002,
    price_label: "$0.002 / remember · $0.001 / recall",
    pricing_model: "per_call",
    depth: "deep",
    implementation_quality: "deep",
    featured: true,
    runtime_live: true,
    when_to_use: "Agent needs durable state across sessions",
    seal: "sealed",
    sample_available: true,
    honesty: { durability: "best_effort", sla: false, trust_scan_passed: false },
  },
  {
    id: "agent-x402-first-buy",
    name: "x402 First Buy Canary",
    summary:
      "Guided first unlock under $0.05 on Base USDC. Proves the pay → sealed pack loop for humans and agents.",
    category: "Onboarding",
    tier: "tripwire",
    price_usd: 0.05,
    price_label: "$0.05 / unlock",
    pricing_model: "unlock",
    depth: "standard",
    implementation_quality: "standard",
    featured: true,
    when_to_use: "Verify payment rails before larger buys",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "aie-premium-access-token",
    name: "AIE Premium Access Token",
    summary: "Tripwire access token with on-chain proof. Confirmed commerce skill used for ledger demos.",
    category: "Commerce",
    tier: "tripwire",
    price_usd: 0.99,
    price_label: "$0.99 / unlock",
    pricing_model: "unlock",
    depth: "standard",
    implementation_quality: "standard",
    featured: true,
    when_to_use: "Need a cheap confirmed unlock for proof",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "lvl-agent-revenue-os",
    name: "LVL Agent Revenue OS Pack",
    summary:
      "Operating system for agent-native revenue: pricing tables, x402 receipts, unlock funnels, and re-download proof.",
    category: "Agent Ops",
    tier: "flagship",
    price_usd: 49,
    price_label: "$49.00 / unlock",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: true,
    when_to_use: "Building a paid agent skill business",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "x402-merchant-operating-system",
    name: "x402 Merchant Operating System",
    summary: "Merchant rails for 402 challenges, settlement verification, and sealed delivery on Base.",
    category: "Commerce",
    tier: "flagship",
    price_usd: 39,
    price_label: "$39.00 / unlock",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: true,
    when_to_use: "Accept agent payments without a browser checkout",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "agent-ops-control-plane",
    name: "Agent Ops Control Plane Pack",
    summary: "Fleet health, spend caps, escalation hooks, and operator dashboards for multi-agent stacks.",
    category: "Agent Ops",
    tier: "premium",
    price_usd: 29,
    price_label: "$29.00 / unlock",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: true,
    when_to_use: "Running many agents with shared spend limits",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "seller-agent",
    name: "Seller Agent",
    summary: "Listing, pricing, negotiation, and fulfillment patterns for autonomous sellers.",
    category: "Commerce",
    tier: "premium",
    price_usd: 24.99,
    price_label: "$24.99 / unlock",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: true,
    when_to_use: "Automating sell-side agent workflows",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "buyer-agent",
    name: "Buyer Agent",
    summary: "Discovery, free sample evaluation, 402 settlement, and inventory tracking for purchasing agents.",
    category: "Commerce",
    tier: "premium",
    price_usd: 24.99,
    price_label: "$24.99 / unlock",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: true,
    when_to_use: "Unattended agent shopping over HTTP",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "agent-auditor",
    name: "Agent Auditor",
    summary: "Post-hoc audit packs for agent decisions: trace IDs, policy checks, escalation recommendations.",
    category: "Trust",
    tier: "premium",
    price_usd: 11.99,
    price_label: "$11.99 / audit pack",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: true,
    when_to_use: "High-stakes agent actions need explainable review",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "escrow-dispute-resolution",
    name: "Escrow & Dispute Resolution for Agent Commerce",
    summary: "Held-fund patterns, dispute windows, and operator moderation keys for open markets.",
    category: "Trust",
    tier: "premium",
    price_usd: 11.99,
    price_label: "$11.99 / unlock",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: false,
    when_to_use: "Third-party listings need escrow",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "deal-pipeline-tracker",
    name: "Deal Pipeline Tracker",
    summary: "Stage machine + CRM-style pipeline for agent-sourced deals with proof of progress.",
    category: "Growth",
    tier: "standard",
    price_usd: 9.99,
    price_label: "$9.99 / unlock",
    pricing_model: "unlock",
    depth: "standard",
    implementation_quality: "standard",
    featured: false,
    when_to_use: "Track multi-step sales or BD loops",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "memory-session-bridge",
    name: "Memory Session Bridge",
    summary: "Patterns for stitching short-term context into durable agent-memory keys without leakage.",
    category: "Memory",
    tier: "standard",
    price_usd: 6.99,
    price_label: "$6.99 / unlock",
    pricing_model: "unlock",
    depth: "standard",
    implementation_quality: "standard",
    featured: false,
    when_to_use: "Connect chat turns to durable KV",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "goal-decomposition-planner",
    name: "Goal Decomposition Planner",
    summary: "Outline for breaking high-level goals into sub-tasks. Outline-only — not featured, starter-capped.",
    category: "Agent Ops",
    tier: "premium", // will be demoted by shelf rules
    price_usd: 7.99,
    price_label: "$7.99 / unlock",
    pricing_model: "unlock",
    depth: "outline_only",
    implementation_quality: "outline_only",
    featured: true, // will be stripped
    when_to_use: "Planning multi-step agent goals",
    seal: "outline",
    sample_available: true,
  },
  {
    id: "observability-telemetry-pack",
    name: "Observability Telemetry Pack",
    summary: "Outline for agent fleet metrics. Demoted from premium featured by shelf honesty rules.",
    category: "Agent Ops",
    tier: "premium",
    price_usd: 7.99,
    price_label: "$7.99 / unlock",
    pricing_model: "unlock",
    depth: "outline_only",
    implementation_quality: "outline_only",
    featured: true,
    when_to_use: "Instrument agent fleets",
    seal: "outline",
    sample_available: true,
  },
  {
    id: "text-to-sql-agent",
    name: "Text-to-SQL Agent",
    summary: "Natural language to SQL outline. Correct category Coding (not Other).",
    category: "Coding",
    tier: "starter",
    price_usd: 2.99,
    price_label: "$2.99 / unlock",
    pricing_model: "unlock",
    depth: "outline_only",
    implementation_quality: "outline_only",
    featured: false,
    when_to_use: "Query structured data from chat",
    seal: "outline",
    sample_available: true,
  },
  {
    id: "swarm-state-manager",
    name: "Swarm State Manager",
    summary: "Outline for multi-agent shared state. Category Agent Ops.",
    category: "Agent Ops",
    tier: "starter",
    price_usd: 2.49,
    price_label: "$2.49 / unlock",
    pricing_model: "unlock",
    depth: "outline_only",
    implementation_quality: "outline_only",
    featured: false,
    when_to_use: "Coordinate swarm checkpoints",
    seal: "outline",
    sample_available: true,
  },
  {
    id: "research-dossier-builder",
    name: "Research Dossier Builder",
    summary: "Deep research pack: sources, claims, and sealed brief structure for agent research runs.",
    category: "Research",
    tier: "premium",
    price_usd: 14.99,
    price_label: "$14.99 / unlock",
    pricing_model: "unlock",
    depth: "deep",
    implementation_quality: "deep",
    featured: false,
    when_to_use: "Produce verifiable research briefs",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "wallet-spend-caps",
    name: "Wallet Spend Caps",
    summary: "Per-skill and fleet spend limits with soft/hard stops for autonomous buyers.",
    category: "Finance",
    tier: "standard",
    price_usd: 8.99,
    price_label: "$8.99 / unlock",
    pricing_model: "unlock",
    depth: "standard",
    implementation_quality: "standard",
    featured: false,
    when_to_use: "Prevent runaway agent spend",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "cold-start-agent-pack",
    name: "Cold-Start Agent Pack",
    summary: "Human + agent onboarding recipes: wallet setup, canary buy, inventory, re-download.",
    category: "Onboarding",
    tier: "standard",
    price_usd: 4.99,
    price_label: "$4.99 / unlock",
    pricing_model: "unlock",
    depth: "standard",
    implementation_quality: "standard",
    featured: false,
    when_to_use: "Onboard new wallets in under 3 minutes",
    seal: "sealed",
    sample_available: true,
  },
  {
    id: "networking-intro-agent",
    name: "Networking Intro Agent",
    summary: "Outreach sequencing and reply classification for B2B intros.",
    category: "Networking",
    tier: "standard",
    price_usd: 9.99,
    price_label: "$9.99 / unlock",
    pricing_model: "unlock",
    depth: "standard",
    implementation_quality: "standard",
    featured: false,
    when_to_use: "Automate careful outreach",
    seal: "sealed",
    sample_available: true,
  },
];

export const SKILLS: Skill[] = RAW.map(applyShelfRules);

export const OPEN_MARKET_COUNT = 3;

export const PROOF = {
  confirmed_unlocks: 1,
  confirmed_volume_usd: 0.99,
  last_skill_id: "aie-premium-access-token",
  last_tx:
    "0x53fe65cf1f3eaca3089cefa23d17259f0c64e777da662211f6c71297c7f9aa1e",
  network: "base",
  asset: "USDC",
} as const;

export function getSkill(id: string): Skill | undefined {
  return SKILLS.find((s) => s.id === id);
}

export function listCategories(skills: Skill[] = SKILLS): string[] {
  const set = new Set(skills.map((s) => s.category));
  return Array.from(set).sort((a, b) => a.localeCompare(b));
}
