/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiProofRouteImport } from './routes/api/proof'
import { Route as ApiShopRouteImport } from './routes/api/shop'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMemoryForgetRouteImport } from './routes/api/memory/forget'
import { Route as ApiMemoryListRouteImport } from './routes/api/memory/list'
import { Route as ApiMemoryPricingRouteImport } from './routes/api/memory/pricing'
import { Route as ApiMemoryRecallRouteImport } from './routes/api/memory/recall'
import { Route as ApiMemoryRememberRouteImport } from './routes/api/memory/remember'
import { Route as ApiSkillsAgentMemoryOutlineRouteImport } from './routes/api/skills/agent-memory/outline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProofRoute = ApiProofRouteImport.update({
  id: '/api/proof',
  path: '/api/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopRoute = ApiShopRouteImport.update({
  id: '/api/shop',
  path: '/api/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryForgetRoute = ApiMemoryForgetRouteImport.update({
  id: '/api/memory/forget',
  path: '/api/memory/forget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryListRoute = ApiMemoryListRouteImport.update({
  id: '/api/memory/list',
  path: '/api/memory/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryPricingRoute = ApiMemoryPricingRouteImport.update({
  id: '/api/memory/pricing',
  path: '/api/memory/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRecallRoute = ApiMemoryRecallRouteImport.update({
  id: '/api/memory/recall',
  path: '/api/memory/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRememberRoute = ApiMemoryRememberRouteImport.update({
  id: '/api/memory/remember',
  path: '/api/memory/remember',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsAgentMemoryOutlineRoute =
  ApiSkillsAgentMemoryOutlineRouteImport.update({
    id: '/api/skills/agent-memory/outline',
    path: '/api/skills/agent-memory/outline',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/status': typeof StatusRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/proof': typeof ApiProofRoute
  '/api/shop': typeof ApiShopRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/pricing': typeof ApiMemoryPricingRoute
  '/api/memory/recall': typeof ApiMemoryRecallRoute
  '/api/memory/remember': typeof ApiMemoryRememberRoute
  '/api/skills/agent-memory/outline': typeof ApiSkillsAgentMemoryOutlineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/status': typeof StatusRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/proof': typeof ApiProofRoute
  '/api/shop': typeof ApiShopRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/pricing': typeof ApiMemoryPricingRoute
  '/api/memory/recall': typeof ApiMemoryRecallRoute
  '/api/memory/remember': typeof ApiMemoryRememberRoute
  '/api/skills/agent-memory/outline': typeof ApiSkillsAgentMemoryOutlineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/status': typeof StatusRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/proof': typeof ApiProofRoute
  '/api/shop': typeof ApiShopRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/pricing': typeof ApiMemoryPricingRoute
  '/api/memory/recall': typeof ApiMemoryRecallRoute
  '/api/memory/remember': typeof ApiMemoryRememberRoute
  '/api/skills/agent-memory/outline': typeof ApiSkillsAgentMemoryOutlineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/marketplace'
    | '/status'
    | '/api/catalog'
    | '/api/health'
    | '/api/inventory'
    | '/api/proof'
    | '/api/shop'
    | '/listings/$id'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/list'
    | '/api/memory/pricing'
    | '/api/memory/recall'
    | '/api/memory/remember'
    | '/api/skills/agent-memory/outline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/marketplace'
    | '/status'
    | '/api/catalog'
    | '/api/health'
    | '/api/inventory'
    | '/api/proof'
    | '/api/shop'
    | '/listings/$id'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/list'
    | '/api/memory/pricing'
    | '/api/memory/recall'
    | '/api/memory/remember'
    | '/api/skills/agent-memory/outline'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/marketplace'
    | '/status'
    | '/api/catalog'
    | '/api/health'
    | '/api/inventory'
    | '/api/proof'
    | '/api/shop'
    | '/listings/$id'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/list'
    | '/api/memory/pricing'
    | '/api/memory/recall'
    | '/api/memory/remember'
    | '/api/skills/agent-memory/outline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  StatusRoute: typeof StatusRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInventoryRoute: typeof ApiInventoryRoute
  ApiProofRoute: typeof ApiProofRoute
  ApiShopRoute: typeof ApiShopRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMemoryForgetRoute: typeof ApiMemoryForgetRoute
  ApiMemoryListRoute: typeof ApiMemoryListRoute
  ApiMemoryPricingRoute: typeof ApiMemoryPricingRoute
  ApiMemoryRecallRoute: typeof ApiMemoryRecallRoute
  ApiMemoryRememberRoute: typeof ApiMemoryRememberRoute
  ApiSkillsAgentMemoryOutlineRoute: typeof ApiSkillsAgentMemoryOutlineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proof': {
      id: '/api/proof'
      path: '/api/proof'
      fullPath: '/api/proof'
      preLoaderRoute: typeof ApiProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop': {
      id: '/api/shop'
      path: '/api/shop'
      fullPath: '/api/shop'
      preLoaderRoute: typeof ApiShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/forget': {
      id: '/api/memory/forget'
      path: '/api/memory/forget'
      fullPath: '/api/memory/forget'
      preLoaderRoute: typeof ApiMemoryForgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/list': {
      id: '/api/memory/list'
      path: '/api/memory/list'
      fullPath: '/api/memory/list'
      preLoaderRoute: typeof ApiMemoryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/pricing': {
      id: '/api/memory/pricing'
      path: '/api/memory/pricing'
      fullPath: '/api/memory/pricing'
      preLoaderRoute: typeof ApiMemoryPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/recall': {
      id: '/api/memory/recall'
      path: '/api/memory/recall'
      fullPath: '/api/memory/recall'
      preLoaderRoute: typeof ApiMemoryRecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/remember': {
      id: '/api/memory/remember'
      path: '/api/memory/remember'
      fullPath: '/api/memory/remember'
      preLoaderRoute: typeof ApiMemoryRememberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/agent-memory/outline': {
      id: '/api/skills/agent-memory/outline'
      path: '/api/skills/agent-memory/outline'
      fullPath: '/api/skills/agent-memory/outline'
      preLoaderRoute: typeof ApiSkillsAgentMemoryOutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  StatusRoute: StatusRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInventoryRoute: ApiInventoryRoute,
  ApiProofRoute: ApiProofRoute,
  ApiShopRoute: ApiShopRoute,
  ListingsIdRoute: ListingsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMemoryForgetRoute: ApiMemoryForgetRoute,
  ApiMemoryListRoute: ApiMemoryListRoute,
  ApiMemoryPricingRoute: ApiMemoryPricingRoute,
  ApiMemoryRecallRoute: ApiMemoryRecallRoute,
  ApiMemoryRememberRoute: ApiMemoryRememberRoute,
  ApiSkillsAgentMemoryOutlineRoute: ApiSkillsAgentMemoryOutlineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
